version: "3.8"
services:
    pg:
        image: postgres:latest
        restart: always
        container_name: pg
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: marquee
        networks:
            - local
    backend:
        build: ./backend
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - pg
        networks:
            - local
    frontend:
        build: ./frontend
        command: npm start
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        restart: always
        ports:
            - "5173:5173"
        networks:
            - local
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - pg
            - backend

networks:
    local:
        driver: bridge
